application: bitbanter
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /heypayme
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always
